
import re

input_file = '/Users/analatkhankhen/Downloads/www/phetcha7_pns2-20260205.sql'
output_file = '/Users/analatkhankhen/Downloads/www/tbl_indicators_import.sql'

with open(input_file, 'r', encoding='utf-8') as f:
    lines = f.readlines()

output_lines = []
in_table_create = False
in_insert = False

# Postgres compatible CREATE TABLE
create_table_sql = """
DROP TABLE IF EXISTS "tbl_indicators";
CREATE TABLE "tbl_indicators" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teach_subject_id" text NOT NULL,
  "grade_level_id" text NOT NULL,
  "content_s_name" text NOT NULL,
  "indicator_group" integer NOT NULL,
  "indicators_name" text NOT NULL,
  "indicator_id" text NOT NULL,
  "indicators_details" text NOT NULL
);

COMMENT ON COLUMN "tbl_indicators"."grade_level_id" IS 'ระดับชั้น';
COMMENT ON COLUMN "tbl_indicators"."content_s_name" IS 'มาตรฐานการเรียนรู้';
COMMENT ON COLUMN "tbl_indicators"."indicator_group" IS 'กลุ่มของตัวชี้วัด';
COMMENT ON COLUMN "tbl_indicators"."indicators_name" IS 'ชื่อตัวชี้วัด';
COMMENT ON COLUMN "tbl_indicators"."indicator_id" IS 'ประเภทตัวชี้วัด';
COMMENT ON COLUMN "tbl_indicators"."indicators_details" IS 'คำอธิบายตัวชี้วัด';

-- Enable Row Level Security
ALTER TABLE "tbl_indicators" ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (adjust as needed)
CREATE POLICY "Enable read access for all users" ON "tbl_indicators" FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON "tbl_indicators" FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON "tbl_indicators" FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON "tbl_indicators" FOR DELETE USING (true);
"""

output_lines.append(create_table_sql)

for line in lines:
    if line.strip().startswith('INSERT INTO `tbl_indicators`'):
        # Normalize column names in INSERT statement
        # Replace backticks with double quotes for table and empty for values if needed, 
        # but Postgres is picky. The values lists are fine.
        # We need to change `tbl_indicators` to "tbl_indicators"
        # and column names `col` to "col"
        
        # MySQL: INSERT INTO `tbl_indicators` (`id`, `teach_subject_id`...) VALUES
        # Postgres: INSERT INTO "tbl_indicators" ("id", "teach_subject_id"...) VALUES
        
        normalized_line = line.replace('`tbl_indicators`', '"tbl_indicators"')
        # Replace column backticks
        normalized_line = re.sub(r'`([^`]+)`', r'"\1"', normalized_line)
        output_lines.append(normalized_line)
        in_insert = True

    elif in_insert:
        # Fix escaped single quotes: \' -> ''
        # The source SQL uses backslash to escape single quotes, but standard SQL uses double single quotes
        fixed_line = line.replace("\\'", "''")
        output_lines.append(fixed_line)
        if line.strip().endswith(';'):
            in_insert = False

with open(output_file, 'w', encoding='utf-8') as f:
    lines_to_write = output_lines + ["\n\n-- Reset identity sequence\nSELECT setval(pg_get_serial_sequence('\"tbl_indicators\"', 'id'), (SELECT MAX(id) FROM \"tbl_indicators\"));\n"]
    f.writelines(lines_to_write)

print(f"Successfully extracted to {output_file}")
