
import re
import sys

def mysql_to_postgres_type(mysql_type):
    mysql_type = mysql_type.lower()
    if 'int' in mysql_type:
        return 'integer'
    if 'varchar' in mysql_type:
        return 'text'
    if 'text' in mysql_type:
        return 'text'
    if 'datetime' in mysql_type:
        return 'timestamp with time zone'
    if 'date' in mysql_type:
        return 'date'
    if 'time' in mysql_type:
        return 'time'
    if 'float' in mysql_type or 'double' in mysql_type:
        return 'double precision'
    if 'decimal' in mysql_type:
        return 'numeric'
    return 'text' # Default fallback

def parse_create_table(sql_content):
    # Find all CREATE TABLE blocks
    # This regex looks for CREATE TABLE `name` (...);
    # It catches the table name and the body
    table_pattern = re.compile(r"CREATE TABLE `(?P<name>.*?)` \((?P<body>.*?)\) ENGINE=.*?;", re.DOTALL)
    
    matches = table_pattern.findall(sql_content)
    
    pg_schema = []
    
    for table_name, body in matches:
        pg_schema.append(f"CREATE TABLE \"{table_name}\" (")
        
        lines = body.split(',\n')
        pg_lines = []
        
        for line in lines:
            line = line.strip()
            if not line: continue
            
            # Remove MySQL COMMENT clauses (not supported in PostgreSQL)
            line = re.sub(r"\s+COMMENT\s+'[^']*'", "", line)
            
            # Skip keys/indices for now (PRIMARY KEY is usually inline or at end)
            if line.startswith('PRIMARY KEY'):
                # Extract primary key column
                pk_match = re.search(r"PRIMARY KEY \(`(.*?)`\)", line)
                if pk_match:
                    pg_lines.append(f"    PRIMARY KEY ({pk_match.group(1)})")
                continue
            if line.startswith('KEY') or line.startswith('UNIQUE KEY') or line.startswith('CONSTRAINT'):
                continue
                
            # Parse column definition
            # `col_name` type constraints
            col_match = re.match(r"`(?P<col>.*?)` (?P<type>.*?) (?P<rest>.*)", line)
            if not col_match:
                # Try match without constraints if they are at the end
                col_match = re.match(r"`(?P<col>.*?)` (?P<type>.*)", line)
            
            if col_match:
                col_name = col_match.group('col')
                mysql_type = col_match.group('type').split(' ')[0] # Get base type
                rest = col_match.group('rest') if 'rest' in col_match.groupdict() and col_match.group('rest') else ''
                
                pg_type = mysql_to_postgres_type(mysql_type)
                
                # Handle AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
                if 'AUTO_INCREMENT' in line:
                     pg_type += " GENERATED BY DEFAULT AS IDENTITY"
                
                # Handle NOT NULL, DEFAULT
                constraints = []
                if 'NOT NULL' in line:
                    constraints.append('NOT NULL')
                if 'DEFAULT' in line:
                    # simplistic default handling
                    default_val = re.search(r"DEFAULT (?P<val>.*)", line)
                    if default_val:
                        val = default_val.group('val').strip().rstrip(',')
                        # Clean up MySQL specific defaults
                        if 'current_timestamp' in val.lower():
                            val = 'now()'
                        constraints.append(f"DEFAULT {val}")
                
                pg_lines.append(f"    \"{col_name}\" {pg_type} {' '.join(constraints)}")
        
        pg_schema.append(",\n".join(pg_lines))
        pg_schema.append(");\n")
        
        # Add simple RLS enable
        pg_schema.append(f"ALTER TABLE \"{table_name}\" ENABLE ROW LEVEL SECURITY;")
        pg_schema.append(f"CREATE POLICY \"Public Read Access\" ON \"{table_name}\" FOR SELECT USING (true);")
        pg_schema.append("\n")

    return "\n".join(pg_schema)

input_file = '/Users/analatkhankhen/Downloads/www/phetcha7_pns2-20260205.sql'
with open(input_file, 'r', encoding='utf-8') as f:
    sql_content = f.read()

pg_sql = parse_create_table(sql_content)

output_file = '/Users/analatkhankhen/.gemini/antigravity/brain/1a88d440-cee2-4e69-ad65-532b3f25b7cc/full_schema_migration.sql'
with open(output_file, 'w', encoding='utf-8') as f:
    f.write("-- Auto-generated PostgreSQL Schema from MySQL Dump\n")
    f.write(pg_sql)

print(f"Generated schema to {output_file}")
