export const allModules = [
  "ManageUserAdmin",
  "reset_user_password",
  "Plan_Check",
  "Plan_scoring",
  "UserAdmin_Add",
  "UserAdmin_Chgpwd",
  "UserAdmin_Edit",
  "ability21",
  "academic_standing",
  "academic_standing_set",
  "appointment",
  "budget_year",
  "budget_year_set",
  "change_position",
  "checkupUser",
  "checkupUserduplicate",
  "chgpasswd",
  "competency",
  "confirmUser",
  "content_standards",
  "content_standards_add",
  "content_standards_edit",
  "dd_edit",
  "desirable",
  "directorschool_edit",
  "editSignature",
  "editprofile",
  "education_level",
  "education_level_set",
  "education_year",
  "education_year_set",
  "gender",
  "grade_level",
  "grade_level_set",
  "importDMC",
  "indicators",
  "indicators_add",
  "indicators_edit",
  "info",
  "supervision_summary",
  "khet",
  "khet_add",
  "khet_edit",
  "khet_remove",
  "learningModel",
  "learningModel_add",
  "learningModel_edit",
  "log",
  "person_position_type",
  "person_position_type_set",
  "person_type",
  "person_type_set",
  "plan_clip",
  "policy_items",
  "policy_number",
  "policy_side",
  "prefix",
  "prefix_set",
  "profile",
  "resetPwd",
  "school",
  "school_add",
  "school_edit",
  "school_remove",
  "school_size",
  "schoolsize_edit",
  "send_clip",
  "sendplan",
  "statusplan",
  "statusplan_clip",
  "statusplan_pass",
  "strands",
  "strands_add",
  "strands_edit",
  "subject_type",
  "subject_type_set",
  "supervisor_edit",
  "tbl_config",
  "teach_subject",
  "teach_subject_set",
  "teacher_edit",
  "type_benchmarks",
  "updatepwd",
  "userDistricDirector",
  "user_remove",
  "userchairman",
  "userdirectorschool",
  "userheadDepartment",
  "usersupervision",
  "usersupervisor",
  "userteacher",
  "view_appointment",
  "view_scoring",
  "nominate_evaluator",
  "approve_evaluator"
];

export const roleModules = {
  chairman: [
    "info",
    "supervision_summary"
  ],
  admin: [
    // Core Management
    "info",
    "supervision_summary",
    "khet",
    "school",
    "budget_year",
    "education_year",

    // User Management
    "confirmUser",
    "checkupUser",
    "checkupUserduplicate",
    "userDistricDirector",
    "usersupervision",
    "usersupervisor",
    "userchairman",
    "userdirectorschool",
    "userheadDepartment",
    "userteacher",
    "change_position",

    // Assessment Configuration
    "policy_side",
    "policy_number",
    "policy_items",

    // Basic Settings  
    "prefix",
    "gender",
    "school_size",
    "teach_subject",
    "academic_standing",
    "subject_type",
    "person_position_type",
    "person_type",
    "education_level",
    "grade_level",
    "type_benchmarks",

    // Learning Content
    "strands",
    "content_standards",
    "indicators",
    "learningModel",
    "competency",
    "ability21",
    "desirable",

    // System Settings
    "tbl_config",
    "profile",
    "chgpasswd",
    "log",
    "importDMC",
    "reset_user_password",
    "approve_evaluator"
  ],
  directorschool: [
    "chgpasswd",
    "editprofile",
    "info",
    "supervision_summary",
    "Plan_Check",
    "Plan_scoring",
    "statusplan",
    "statusplan_clip",
    "statusplan_pass",
    "view_scoring",
    "nominate_evaluator"
  ],
  headdepartment: [
    "info",
    "supervision_summary",
    "Plan_Check",
    "Plan_scoring",
    "view_scoring"
  ],
  root: [
    "ManageUserAdmin",
    "info",
    "supervision_summary"
  ],
  supervision: [
    "info",
    "supervision_summary",
    "Plan_Check",
    "Plan_scoring",
    "view_scoring"
  ],
  districdirector: [
    "chgpasswd",
    "editprofile",
    "info",
    "supervision_summary"
  ],
  teacher: [
    "chgpasswd",
    "editSignature",
    "editprofile",
    "info",
    "supervision_summary",
    "sendplan",
    "statusplan",
    "statusplan_clip",
    "view_scoring"
  ],
  supervisor: [
    "chgpasswd",
    "info",
    "supervision_summary"
  ]
};

export const moduleLabels = {
  info: "หน้าหลัก",
  supervision_summary: "สรุปผลการนิเทศ Coding ปี 2568",
  confirmUser: "ผู้ใช้งานรอการอนุมัติ",
  checkupUser: "ข้อมูลผู้ใช้ผิดพลาด",
  checkupUserduplicate: "เลขประจำตัวประชาชนซ้ำ",
  userDistricDirector: "ผู้อำนวยการเขตพื้นที่",
  usersupervision: "ผู้ประเมิน",
  usersupervisor: "ศึกษานิเทศก์",
  userchairman: "ประธานสหวิทยาเขต",
  userdirectorschool: "ผอ.โรงเรียน/รอง ผอ.",
  userheadDepartment: "หัวหน้ากลุ่มสาระโรงเรียน",
  userteacher: "ครู",
  change_position: "เปลี่ยนตำแหน่ง",
  policy_side: "ด้านการประเมิน",
  policy_number: "ตัวชี้วัด การประเมิน",
  policy_items: "รายละเอียด การประเมิน",
  prefix: "คำนำหน้า",
  prefix_set: "ตั้งค่าคำนำหน้า",
  gender: "เพศ",
  school_size: "ขนาดโรงเรียน",
  schoolsize_edit: "แก้ไขขนาดโรงเรียน",
  khet: "จัดการสหวิทยาเขต",
  khet_add: "เพิ่มสหวิทยาเขต",
  khet_edit: "แก้ไขสหวิทยาเขต",
  khet_remove: "ลบสหวิทยาเขต",
  school: "จัดการโรงเรียน",
  school_add: "เพิ่มโรงเรียน",
  school_edit: "แก้ไขโรงเรียน",
  school_remove: "ลบโรงเรียน",
  budget_year: "จัดการปีงบประมาณ",
  budget_year_set: "ตั้งค่าปีงบประมาณ",
  education_year: "จัดการปีการศึกษา",
  education_year_set: "ตั้งค่าปีการศึกษา",
  teach_subject: "กลุ่มสาระการเรียนรู้",
  teach_subject_set: "ตั้งค่ากลุ่มสาระการเรียนรู้",
  academic_standing: "วิทยฐานะทางวิชาการ",
  academic_standing_set: "ตั้งค่าวิทยฐานะ",
  subject_type: "ประเภทรายวิชา",
  subject_type_set: "ตั้งค่าประเภทรายวิชา",
  person_position_type: "ชื่อตำแหน่ง",
  person_position_type_set: "ตั้งค่าชื่อตำแหน่ง",
  person_type: "ประเภทบุคลากร",
  person_type_set: "ตั้งค่าประเภทบุคลากร",
  education_level: "ระดับการศึกษา",
  education_level_set: "ตั้งค่าระดับการศึกษา",
  grade_level: "ระดับชั้น",
  grade_level_set: "ตั้งค่าระดับชั้น",
  type_benchmarks: "ประเภทตัวชี้วัด",
  strands: "สาระการเรียนรู้",
  content_standards: "มาตรฐานการเรียนรู้",
  indicators: "ตัวชี้วัด",
  learningModel: "รูปแบบการจัดการเรียนรู้",
  competency: "สมรรถนะผู้เรียน",
  ability21: "ทักษะในศตวรรษที่ 21",
  desirable: "คุณลักษณะอันพึงประสงค์",
  tbl_config: "ตั้งค่าระบบ",
  profile: "ปรับปรุงข้อมูลส่วนตัว",
  chgpasswd: "เปลี่ยนรหัสผ่าน",
  log: "ข้อมูลการเข้าระบบ",
  importDMC: "Import From DMC",
  statusplan: "สถานะแผนการสอน",
  sendplan: "ส่งแผนการสอน",
  statusplan_clip: "ส่งคลิปการสอน",
  editprofile: "ข้อมูลส่วนตัว",
  editSignature: "จัดการลายเซ็นต์",
  statusplan_pass: "แผนการสอนตรวจแล้ว",
  ManageUserAdmin: "จัดการผู้จัดการระบบ",
  Plan_Check: "ตรวจแผนการสอน",
  Plan_scoring: "การประเมินแผนการสอน",
  appointment: "ตรวจแผนการสอน/แต่งตั้งกรรมการ",
  view_appointment: "ดูข้อมูลแผนการสอน",
  plan_clip: "คลิปการสอน",
  UserAdmin_Add: "เพิ่มผู้ดูแลระบบ",
  UserAdmin_Edit: "แก้ไขผู้ดูแลระบบ",
  UserAdmin_Chgpwd: "เปลี่ยนรหัสผ่านผู้ดูแลระบบ",
  teacher_edit: "แก้ไขข้อมูลครู",
  directorschool_edit: "แก้ไขข้อมูลผู้บริหาร",
  supervisor_edit: "แก้ไขข้อมูลศึกษานิเทศ",
  dd_edit: "แก้ไขข้อมูลผอ.เขต",
  resetPwd: "Reset รหัสผ่าน",
  reset_user_password: "Reset รหัสผ่านบุคลากร",
  updatepwd: "อัปเดตรหัสผ่าน",
  send_clip: "ส่งคลิป (เก่า)",
  view_scoring: "ดูคะแนนการประเมิน",
  nominate_evaluator: "เสนอแต่งตั้งผู้นิเทศ",
  approve_evaluator: "อนุมัติผู้นิเทศ"
};

export const moduleIcons = {
  info: "fa-solid fa-house-chimney text-blue",
  supervision_summary: "fa-solid fa-chart-pie text-success",
  confirmUser: "fa-solid fa-user-check text-success",
  sendplan: "nav-icon fa-regular fa-paper-plane text-success",
  statusplan_clip: "nav-icon fa-brands fa-youtube text-danger",
  send_clip: "nav-icon fa-solid fa-video text-danger",
  editprofile: "nav-icon fa-solid fa-address-card text-warning",
  editSignature: "nav-icon fa-solid fa-signature text-info",
  chgpasswd: "nav-icon fa-solid fa-key text-danger",
  view_scoring: "nav-icon fa-solid fa-star text-warning",
  appointment: "nav-icon fas fa-clipboard-check text-success",
  plan_clip: "nav-icon fas fa-film text-danger",
  statusplan_pass: "nav-icon fas fa-check-double text-success",
  view_appointment: "nav-icon fas fa-eye text-info",
  Plan_Check: "nav-icon fas fa-clipboard-list text-primary",
  Plan_scoring: "nav-icon fas fa-star-half-stroke text-warning",

  // Core Management
  khet: "nav-icon fa-solid fa-school-circle-check text-danger",
  school: "nav-icon fa-solid fa-school text-success",
  budget_year: "nav-icon fa-solid fa-baht-sign text-warning",
  education_year: "nav-icon fa-solid fa-school-flag text-blue",

  // User Management
  confirmUser: "nav-icon fa-solid fa-person-circle-check text-danger",
  checkupUser: "nav-icon fa-solid fa-triangle-exclamation text-danger",
  checkupUserduplicate: "nav-icon fa-solid fa-triangle-exclamation text-danger",
  userDistricDirector: "nav-icon fa-solid fa-user-tie text-primary",
  usersupervision: "nav-icon fa-solid fa-user-check text-success",
  usersupervisor: "nav-icon fa-solid fa-user-graduate text-info",
  userchairman: "nav-icon fa-solid fa-user-shield text-warning",
  userdirectorschool: "nav-icon fa-solid fa-user-gear text-danger",
  userheadDepartment: "nav-icon fa-solid fa-users text-primary",
  userteacher: "nav-icon fa-solid fa-chalkboard-user text-success",
  change_position: "nav-icon fa-solid fa-person-booth text-blue",
  user_remove: "nav-icon fa-solid fa-user-slash text-danger",
  resetPwd: "nav-icon fa-solid fa-unlock-keyhole text-warning",
  reset_user_password: "nav-icon fa-solid fa-key text-danger",

  // Assessment Configuration
  policy_side: "nav-icon fa-solid fa-list-check text-primary",
  policy_number: "nav-icon fa-solid fa-hashtag text-info",
  policy_items: "nav-icon fa-solid fa-clipboard-list text-success",

  // Basic Settings
  prefix: "nav-icon fa-solid fa-mars-double text-primary",
  gender: "nav-icon fa-solid fa-person text-info",
  school_size: "nav-icon fa-solid fa-chart-simple text-success",
  teach_subject: "nav-icon fa-solid fa-graduation-cap text-primary",
  academic_standing: "nav-icon fa-solid fa-award text-warning",
  subject_type: "nav-icon fa-solid fa-book text-info",
  person_position_type: "nav-icon fa-solid fa-briefcase text-primary",
  person_type: "nav-icon fa-solid fa-users-gear text-success",
  education_level: "nav-icon fa-solid fa-layer-group text-info",
  grade_level: "nav-icon fa-solid fa-stairs text-primary",
  type_benchmarks: "nav-icon fa-solid fa-chart-line text-success",

  // Learning Content
  strands: "nav-icon fa-solid fa-book-open text-primary",
  content_standards: "nav-icon fa-solid fa-list-ol text-info",
  indicators: "nav-icon fa-solid fa-bullseye text-success",
  learningModel: "nav-icon fa-solid fa-diagram-project text-warning",
  competency: "nav-icon fa-solid fa-brain text-primary",
  ability21: "nav-icon fa-solid fa-rocket text-danger",
  desirable: "nav-icon fa-solid fa-heart text-danger",

  // System Settings
  tbl_config: "nav-icon fa-solid fa-gears text-info",
  profile: "nav-icon fa-solid fa-user-gear text-info",
  updatepwd: "nav-icon fa-solid fa-key-skeleton text-warning",
  log: "nav-icon fa-solid fa-anchor-lock text-warning",
  importDMC: "nav-icon fa-solid fa-file-import text-success",
  nominate_evaluator: "nav-icon fas fa-user-plus text-primary",
  approve_evaluator: "nav-icon fas fa-user-check text-success"
};

